/*
 * Copyright (c) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { Browser } from '../model/Browser'
import { WebTab, BrowserTabs } from './TitleBar'
import Logger from '../model/Logger'

interface ButtonItem {
  imageSrc: Resource
  id: number
}

const TAG: string = '[PhoneLayout]'
const BUTTON_WIDTH: number = 22
const BUTTON_RADIUS: number = 4
const DOWN_COLOR: string = '#e4e4e4'
const UP_COLOR: string = '#00000000'

@Component
export struct PhoneLayout {
  @Link browser: Browser;
  @State isPhone: boolean = true;
  @State hasDown: boolean = false;
  @State pageCount: string = '1';
  @State arrayIndex: number = 0;
  // @State hideToolBar: boolean = false;

  private addr: string = ''
  private toolPoneArray: Array<ButtonItem> = [
    {
      imageSrc: $r('app.media.ic_public_back'),
      id: 1
    } as ButtonItem,
    {
      imageSrc: $r('app.media.ic_public_advance'),
      id: 2
    } as ButtonItem,
    {
      imageSrc: $r('app.media.ic_public_home'),
      id: 5
    } as ButtonItem,
    {
      imageSrc: $r('app.media.ic_public_refresh'),
      id: 3
    } as ButtonItem,
    {
      imageSrc: $r('app.media.ic_public_add'),
      id: 6
    } as ButtonItem
  ]

  @Builder ToolBar() {
    Column() {
      // Divider().height(0.5).color('#e9eaec')
      if (!this.browser.hideProgress) {
        Progress({ value: this.browser.progress, total: 100 })
          .color('#0000ff').width('100%').height(2)
      } else {
        Column().backgroundColor('#fdfdfd').width('100%').height(2)
      }
      Row() {
        ForEach(this.toolPoneArray, (item: ButtonItem) => {
          Column() {
            Button({ type: ButtonType.Normal }) {
              Column() {
                if (item.id !== 4) {
                  Image(item.imageSrc)
                } else {
                  Column() {
                    Text(this.pageCount)
                      .fontSize(16)
                  }
                  .border({ width: 2 })
                  .width(22)
                  .height(22)
                  .borderRadius(5)
                  .justifyContent(FlexAlign.Center)
                }
              }
              .width(BUTTON_WIDTH)
              .height(BUTTON_WIDTH)
              .justifyContent(FlexAlign.Center)
            }
            .height('100%')
            .width('100%')
            .backgroundColor(this.arrayIndex === item.id ? DOWN_COLOR : UP_COLOR)
            .borderRadius(BUTTON_RADIUS)
            .flexShrink(0)
            .onTouch((event: TouchEvent) => {
              if (event.type === TouchType.Down) {
                this.arrayIndex = item.id
              } else if (event.type === TouchType.Up) {
                this.arrayIndex = 0
              }
            })
            .onClick((event: ClickEvent) => {
              switch (item.id) {
                case 1:
                  this.browser.Back()
                  break;
                case 2:
                  this.browser.Forward()
                  break;
                case 3:
                  this.browser.Refresh()
                  break;
                case 5:
                  this.browser.webControllerArray[this.browser.tabArrayIndex].controller.loadUrl($rawfile('phone.html'))
                  break;
                case 6:
                  Logger.info(TAG, `add tab index = ` + this.arrayIndex)
                  this.browser.addTab()
                  break;
                default:
                  break;
              }
            })
          }
          .width('18%')
        })
      }
      .justifyContent(FlexAlign.SpaceAround)
      .width('100%')
      .height(54)
      .padding({bottom: 2})
      .backgroundColor('#fdfdfd')
    }
    .backgroundColor('#fdfdfd')
    .height('100%')
    .border({width: {top: 0.5}, color: '#d3d3d3'})
  }

  build() {
    Column() {
      Navigation() {
        Column() {
          Row() {
            TextInput({ placeholder: $r('app.string.placeholder_enter_url'), text: this.browser.inputValue })
              // 字体太大被遮挡，调成14
              .placeholderFont({ size: 14, weight: 500 })
              .fontSize(14)
              .margin(2)
              // 垂直居中效果更好，改为32
              .height(32)
              .onChange((value: string) => {
                Logger.info(TAG, `onChange`)
                this.addr = value
              })
              .onSubmit((enterKey: EnterKeyType) => {
                Logger.info(TAG, `onSubmit`)
                this.browser.webControllerArray[this.browser.tabArrayIndex].controller.loadUrl(this.addr)
                this.addr = ''
              })
            Button({ type: ButtonType.Normal }) {
              Image($r('app.media.submit'))
            }
            .margin(8)
            .width(BUTTON_WIDTH)
            .height(BUTTON_WIDTH)
            .backgroundColor(this.hasDown ? DOWN_COLOR : UP_COLOR)
            .borderRadius(BUTTON_RADIUS)
            .flexShrink(0)
            .onTouch((event: TouchEvent) => {
              if (event.type === TouchType.Down) {
                this.hasDown = true
              } else if (event.type === TouchType.Up) {
                this.hasDown = false
              }
            })
            .onClick((event: ClickEvent) => {
              this.browser.loadUrl(this.addr)
              this.addr = ''
            })
          }

          // Add tab bar for phone layout
          BrowserTabs({ browser: $browser })
          Divider().color('#c6c6c6').width('100%').flexShrink(0)

          Column() {
            WebTab({ browser: $browser, isPhone: $isPhone })
            // WebTab({ browser: $browser, isPhone: $isPhone, hideToolBar: $hideToolBar })
          }
        }
      }
      .hideTitleBar(true)
      .hideBackButton(true)
      .toolBar(this.ToolBar)
      // .hideToolBar(this.hideToolBar)
    }
  }
}